Issue displaying date type columns on main grid
Probably caused by the Magento 2.4.0 update, it seems that using the "timezone" configuration in the date type columns results in a knockout.js error visible in console, that makes impossible to view the grid correctly. Removing it seems to work fine.
The error is the following:
"Uncaught TypeError: Unable to process binding "text: function(){return $col.getLabel($row()) }"
Message: (intermediate value).toLowerCase is not a function" in file moment-timezone-with-data.js